"""
Common data fetching utilities and shared constants.

Data strategy (transparent to callers):
  1. Check Supabase cache — if fresh, return cached data (zero API calls)
  2. Fetch from yfinance (free, reliable for historical)
  3. If yfinance data is stale (>1 min), fill gap with Upstox real-time
  4. Cache result in Supabase for future calls
  5. Degrade gracefully if Upstox/Supabase unavailable
"""

import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timedelta, timezone
from pathlib import Path
from threading import Lock

import pandas as pd
import yfinance as yf

# ── Parallel fetch throttle ──────────────────────────────────────────────
_yf_lock = Lock()
_YF_MIN_INTERVAL = 0.15  # seconds between yfinance API calls (avoids 429s)
_yf_last_call = 0.0

IST = timezone(timedelta(hours=5, minutes=30))

# ── Project paths ─────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.parent

# Module-specific paths — each scanner's outputs live inside its own package
SCALP_DIR = PROJECT_ROOT / "scalp"
SCALP_OUTPUT_DIR = SCALP_DIR / "output"
SCALP_CONFIG_PATH = SCALP_DIR / "scalp_config.yaml"
SCALP_REPORT_DIR = SCALP_DIR / "reports"

BTST_DIR = PROJECT_ROOT / "btst"
BTST_REPORT_DIR = BTST_DIR / "reports"

INTRADAY_DIR = PROJECT_ROOT / "intraday"
INTRADAY_REPORT_DIR = INTRADAY_DIR / "reports"

# Legacy aliases (for backwards compat during transition)
OUTPUT_DIR = SCALP_OUTPUT_DIR
CONFIG_PATH = SCALP_CONFIG_PATH

# ── Configuration ─────────────────────────────────────────────────────────

# Universe loading: prefers universe.yaml (generated by `python -m common.universe`),
# falls back to hardcoded dict below.

_UNIVERSE_PATH = PROJECT_ROOT / "common" / "universe.yaml"

_HARDCODED_TICKERS = {
    # ── Banks (14) ──
    "HDFCBANK.NS":    {"sector": "^NSEBANK",   "name": "HDFC Bank"},
    "ICICIBANK.NS":   {"sector": "^NSEBANK",   "name": "ICICI Bank"},
    "SBIN.NS":        {"sector": "^NSEBANK",   "name": "State Bank of India"},
    "KOTAKBANK.NS":   {"sector": "^NSEBANK",   "name": "Kotak Mahindra Bank"},
    "AXISBANK.NS":    {"sector": "^NSEBANK",   "name": "Axis Bank"},
    "INDUSINDBK.NS":  {"sector": "^NSEBANK",   "name": "IndusInd Bank"},
    "BANKBARODA.NS":  {"sector": "^NSEBANK",   "name": "Bank of Baroda"},
    "PNB.NS":         {"sector": "^NSEBANK",   "name": "Punjab National Bank"},
    "CANBK.NS":       {"sector": "^NSEBANK",   "name": "Canara Bank"},
    "UNIONBANK.NS":   {"sector": "^NSEBANK",   "name": "Union Bank of India"},
    "FEDERALBNK.NS":  {"sector": "^NSEBANK",   "name": "Federal Bank"},
    "IDFCFIRSTB.NS":  {"sector": "^NSEBANK",   "name": "IDFC First Bank"},
    "AUBANK.NS":      {"sector": "^NSEBANK",   "name": "AU Small Finance Bank"},
    "IDBI.NS":        {"sector": "^NSEBANK",   "name": "IDBI Bank"},  # borderline ATR ~8%, watch monthly
    # ── Financials / Insurance / NBFC (14) ──
    "SAILIFE.NS":     {"sector": "^CNXFIN",    "name": "SBI Life Insurance"},
    "SBILIFE.NS":     {"sector": "^CNXFIN",    "name": "SBI Life Insurance Co"},
    "HDFCLIFE.NS":    {"sector": "^CNXFIN",    "name": "HDFC Life Insurance"},
    "BAJFINANCE.NS":  {"sector": "^CNXFIN",    "name": "Bajaj Finance"},
    "BAJAJFINSV.NS":  {"sector": "^CNXFIN",    "name": "Bajaj Finserv"},
    "KFINTECH.NS":    {"sector": "^CNXFIN",    "name": "KFin Technologies"},
    "CAMS.NS":        {"sector": "^CNXFIN",    "name": "Computer Age Mgmt Services"},
    "BSE.NS":         {"sector": "^CNXFIN",    "name": "BSE Limited"},
    "PFC.NS":         {"sector": "^CNXFIN",    "name": "Power Finance Corp"},
    "RECLTD.NS":      {"sector": "^CNXFIN",    "name": "REC Limited"},
    "ABCAPITAL.NS":   {"sector": "^CNXFIN",    "name": "Aditya Birla Capital"},
    "INDIANB.NS":     {"sector": "^CNXFIN",    "name": "Indian Bank"},
    "BAJAJHFL.NS":    {"sector": "^CNXFIN",    "name": "Bajaj Housing Finance"},
    "SHRIRAMFIN.NS":  {"sector": "^CNXFIN",    "name": "Shriram Finance"},
    "MCX.NS":         {"sector": "^CNXFIN",    "name": "Multi Commodity Exchange"},
    "JIOFIN.NS":      {"sector": "^CNXFIN",    "name": "Jio Financial Services"},
    # ── Energy / Oil & Gas / Power (14) ──
    "RELIANCE.NS":    {"sector": "^CNXENERGY", "name": "Reliance Industries"},
    "TATAPOWER.NS":   {"sector": "^CNXENERGY", "name": "Tata Power"},
    "ADANIPOWER.NS":  {"sector": "^CNXENERGY", "name": "Adani Power"},
    "NTPC.NS":        {"sector": "^CNXENERGY", "name": "NTPC"},
    "COALINDIA.NS":   {"sector": "^CNXENERGY", "name": "Coal India"},
    "IOC.NS":         {"sector": "^CNXENERGY", "name": "Indian Oil Corporation"},
    "BPCL.NS":        {"sector": "^CNXENERGY", "name": "Bharat Petroleum"},
    "HINDPETRO.NS":   {"sector": "^CNXENERGY", "name": "Hindustan Petroleum"},
    "ONGC.NS":        {"sector": "^CNXENERGY", "name": "Oil & Natural Gas Corp"},
    "GAIL.NS":        {"sector": "^CNXENERGY", "name": "GAIL (India)"},
    "ADANIGREEN.NS":  {"sector": "^CNXENERGY", "name": "Adani Green Energy"},
    "JSWENERGY.NS":   {"sector": "^CNXENERGY", "name": "JSW Energy"},
    "POWERGRID.NS":   {"sector": "^CNXENERGY", "name": "Power Grid Corporation"},
    "ADANIENSOL.NS":  {"sector": "^CNXENERGY", "name": "Adani Energy Solutions"},
    # ── Metals / Mining (9) ──
    "JSWSTEEL.NS":    {"sector": "^CNXMETAL",  "name": "JSW Steel"},
    "TATASTEEL.NS":   {"sector": "^CNXMETAL",  "name": "Tata Steel"},
    "JINDALSTEL.NS":  {"sector": "^CNXMETAL",  "name": "Jindal Steel & Power"},
    "HINDALCO.NS":    {"sector": "^CNXMETAL",  "name": "Hindalco Industries"},
    "HINDZINC.NS":    {"sector": "^CNXMETAL",  "name": "Hindustan Zinc"},
    "VEDL.NS":        {"sector": "^CNXMETAL",  "name": "Vedanta"},
    "GPIL.NS":        {"sector": "^CNXMETAL",  "name": "Godawari Power & Ispat"},
    "ADANIENT.NS":    {"sector": "^CNXMETAL",  "name": "Adani Enterprises"},
    "GRAPHITE.NS":    {"sector": "^CNXMETAL",  "name": "Graphite India"},
    # ── PSE / Defence (9) ──
    "BEL.NS":         {"sector": "^CNXPSE",    "name": "Bharat Electronics"},
    "BHEL.NS":        {"sector": "^CNXPSE",    "name": "Bharat Heavy Electricals"},
    "HAL.NS":         {"sector": "^CNXPSE",    "name": "Hindustan Aeronautics"},
    "MAZDOCK.NS":     {"sector": "^CNXPSE",    "name": "Mazagon Dock Shipbuilders"},
    "DATAPATTNS.NS":  {"sector": "^CNXPSE",    "name": "Data Patterns"},
    "MTARTECH.NS":    {"sector": "^CNXPSE",    "name": "MTAR Technologies"},
    "SCI.NS":         {"sector": "^CNXPSE",    "name": "Shipping Corp of India"},
    "RVNL.NS":        {"sector": "^CNXPSE",    "name": "Rail Vikas Nigam"},
    "COCHINSHIP.NS":  {"sector": "^CNXPSE",    "name": "Cochin Shipyard"},
    # ── Infra / Capital Goods (11) ──
    "ADANIPORTS.NS":  {"sector": "^CNXINFRA",  "name": "Adani Ports"},
    "LT.NS":          {"sector": "^CNXINFRA",  "name": "Larsen & Toubro"},
    "SIEMENS.NS":     {"sector": "^CNXINFRA",  "name": "Siemens"},
    "ABB.NS":         {"sector": "^CNXINFRA",  "name": "ABB India"},
    "CGPOWER.NS":     {"sector": "^CNXINFRA",  "name": "CG Power & Industrial"},
    "CUMMINSIND.NS":  {"sector": "^CNXINFRA",  "name": "Cummins India"},
    "HAVELLS.NS":     {"sector": "^CNXINFRA",  "name": "Havells India"},
    "NBCC.NS":        {"sector": "^CNXINFRA",  "name": "NBCC (India)"},
    "FINCABLES.NS":   {"sector": "^CNXINFRA",  "name": "Finolex Cables"},
    "AMBUJACEM.NS":   {"sector": "^CNXINFRA",  "name": "Ambuja Cements"},
    "GRASIM.NS":      {"sector": "^CNXINFRA",  "name": "Grasim Industries"},
    # ── IT (8) ──
    "TCS.NS":         {"sector": "^CNXIT",     "name": "Tata Consultancy Services"},
    "INFY.NS":        {"sector": "^CNXIT",     "name": "Infosys"},
    "HCLTECH.NS":     {"sector": "^CNXIT",     "name": "HCL Technologies"},
    "TECHM.NS":       {"sector": "^CNXIT",     "name": "Tech Mahindra"},
    "WIPRO.NS":       {"sector": "^CNXIT",     "name": "Wipro"},
    "NETWEB.NS":      {"sector": "^CNXIT",     "name": "Netweb Technologies"},
    "HAPPSTMNDS.NS":  {"sector": "^CNXIT",     "name": "Happiest Minds Technologies"},
    "NAUKRI.NS":      {"sector": "^CNXIT",     "name": "Info Edge (Naukri)"},
    # ── Telecom (1) ──
    "BHARTIARTL.NS":  {"sector": "^CNXIT",     "name": "Bharti Airtel"},  # no NSE telecom index, park under IT
    # ── Auto / Auto Ancillary (8) ──
    "M&M.NS":         {"sector": "^CNXAUTO",   "name": "Mahindra & Mahindra"},
    "BAJAJ-AUTO.NS":  {"sector": "^CNXAUTO",   "name": "Bajaj Auto"},
    "EICHERMOT.NS":   {"sector": "^CNXAUTO",   "name": "Eicher Motors"},
    "TVSMOTOR.NS":    {"sector": "^CNXAUTO",   "name": "TVS Motor Company"},
    "MOTHERSON.NS":   {"sector": "^CNXAUTO",   "name": "Motherson Sumi Systems"},
    "EXIDEIND.NS":    {"sector": "^CNXAUTO",   "name": "Exide Industries"},
    "TMPV.NS":        {"sector": "^CNXAUTO",   "name": "Tata Motors Passenger Vehicles"},
    # ── FMCG / Consumer (12) ──
    "HINDUNILVR.NS":  {"sector": "^CNXFMCG",   "name": "Hindustan Unilever"},
    "ITC.NS":         {"sector": "^CNXFMCG",   "name": "ITC"},
    "TRENT.NS":       {"sector": "^CNXFMCG",   "name": "Trent"},
    "TITAN.NS":       {"sector": "^CNXFMCG",   "name": "Titan Company"},
    "NESTLEIND.NS":   {"sector": "^CNXFMCG",   "name": "Nestle India"},
    "BRITANNIA.NS":   {"sector": "^CNXFMCG",   "name": "Britannia Industries"},
    "TATACONSUM.NS":  {"sector": "^CNXFMCG",   "name": "Tata Consumer Products"},
    "PIDILITIND.NS":  {"sector": "^CNXFMCG",   "name": "Pidilite Industries"},
    "ASIANPAINT.NS":  {"sector": "^CNXFMCG",   "name": "Asian Paints"},
    "VBL.NS":         {"sector": "^CNXFMCG",   "name": "Varun Beverages"},
    "UNITDSPR.NS":    {"sector": "^CNXFMCG",   "name": "United Spirits"},
    "GODREJCP.NS":    {"sector": "^CNXFMCG",   "name": "Godrej Consumer Products"},
    "ETERNAL.NS":     {"sector": "^CNXFMCG",   "name": "Eternal (Zomato)"},
    "FIRSTCRY.NS":    {"sector": "^CNXFMCG",   "name": "FirstCry"},
    "INDHOTEL.NS":    {"sector": "^CNXFMCG",   "name": "Indian Hotels"},
    "DMART.NS":       {"sector": "^CNXFMCG",   "name": "Avenue Supermarts (DMart)"},
    # ── Realty (3) ──
    "DLF.NS":         {"sector": "^CNXREALTY",  "name": "DLF"},
    "ANANTRAJ.NS":    {"sector": "^CNXREALTY",  "name": "Anant Raj"},
    "LODHA.NS":       {"sector": "^CNXREALTY",  "name": "Macrotech Developers"},
    # ── Pharma / Healthcare (8) ──
    "SUNPHARMA.NS":   {"sector": "^CNXPHARMA", "name": "Sun Pharma Industries"},
    "DRREDDY.NS":     {"sector": "^CNXPHARMA", "name": "Dr. Reddy's Laboratories"},
    "CIPLA.NS":       {"sector": "^CNXPHARMA", "name": "Cipla"},
    "DIVISLAB.NS":    {"sector": "^CNXPHARMA", "name": "Divi's Laboratories"},
    "APOLLOHOSP.NS":  {"sector": "^CNXPHARMA", "name": "Apollo Hospitals"},
    "GLENMARK.NS":    {"sector": "^CNXPHARMA", "name": "Glenmark Pharmaceuticals"},
    "TORNTPHARM.NS":  {"sector": "^CNXPHARMA", "name": "Torrent Pharmaceuticals"},
    "ZYDUSLIFE.NS":   {"sector": "^CNXPHARMA", "name": "Zydus Lifesciences"},
    # ── Airlines (1) ──
    "INDIGO.NS":      {"sector": "^CNXINFRA",  "name": "InterGlobe Aviation"},  # no airline index, park under infra
    # ── Industrial / Other (5) ──
    "AEROFLEX.NS":    {"sector": "^CNXMETAL",  "name": "Aeroflex Industries"},
    "GUJALKALI.NS":   {"sector": "^CNXMETAL",  "name": "Gujarat Alkalies & Chemicals"},
    "GMDCLTD.NS":     {"sector": "^CNXMETAL",  "name": "Gujarat Mineral Dev Corp"},
    "AETHER.NS":      {"sector": "^CNXPHARMA", "name": "Aether Industries"},
    "LICI.NS":        {"sector": "^CNXFIN",    "name": "Life Insurance Corp"},
}


def _load_universe(tier=None):
    """Load trade universe from universe.yaml.

    Args:
        tier: If set ("scalp", "intraday", "btst"), only include stocks
              eligible for that tier. If None, include all stocks.

    Returns dict in TICKERS format: {yf_symbol: {"sector": ..., "name": ...}}
    """
    if not _UNIVERSE_PATH.exists():
        return None
    try:
        import yaml
        with open(_UNIVERSE_PATH) as f:
            universe = yaml.safe_load(f)
        if not universe or "stocks" not in universe:
            return None

        tickers = {}
        for sym, data in universe["stocks"].items():
            if tier and not data.get("eligible", {}).get(tier, False):
                continue
            tickers[sym] = {
                "sector": data.get("sector", "^CNXINFRA"),
                "name": data.get("name", sym.replace(".NS", "")),
            }
        return tickers if tickers else None
    except Exception:
        return None


def load_universe_for_tier(tier):
    """Load stocks eligible for a specific tier. Falls back to hardcoded TICKERS.

    Set USE_UNIVERSE = True to enable dynamic universe from universe.yaml.
    When False (default), always uses the hardcoded 34-stock list.

    Usage in scanners:
        from common.data import load_universe_for_tier
        stocks = load_universe_for_tier("scalp")
    """
    if USE_UNIVERSE:
        return _load_universe(tier=tier) or _HARDCODED_TICKERS
    return _HARDCODED_TICKERS


# Toggle: set True to use universe.yaml, False to always use hardcoded tickers
USE_UNIVERSE = False

# Default TICKERS: hardcoded list (or universe if enabled)
TICKERS = load_universe_for_tier("intraday")

BENCHMARK = "^NSEI"  # Nifty 50

IST_WINDOWS = [
    ("09:15", "10:00"),
    ("10:00", "11:30"),
    ("11:30", "12:30"),
    ("12:30", "13:30"),
    ("13:30", "14:30"),
    ("14:30", "15:15"),
]

GAP_THRESHOLDS = {"flat": 0.003, "small": 0.01}
TARGET_PCTS = [0.5, 1.0, 1.5, 2.0]
STOP_PCTS = [0.5, 1.0, 1.5]


# ── Data Fetching ─────────────────────────────────────────────────────────

def _throttle_yf():
    """Thread-safe throttle to space out yfinance API calls."""
    global _yf_last_call
    with _yf_lock:
        now = time.monotonic()
        elapsed = now - _yf_last_call
        if elapsed < _YF_MIN_INTERVAL:
            time.sleep(_YF_MIN_INTERVAL - elapsed)
        _yf_last_call = time.monotonic()


def _fetch_yfinance(symbol, period, interval, max_retries=3):
    """Raw yfinance download with retries. No caching."""
    for attempt in range(max_retries):
        try:
            _throttle_yf()
            df = yf.download(symbol, period=period, interval=interval, progress=False)
            if df.empty:
                return pd.DataFrame()
            # yfinance may return MultiIndex columns — flatten to single level
            if isinstance(df.columns, pd.MultiIndex):
                # If only one ticker, just drop the Ticker level
                if df.columns.get_level_values("Ticker").nunique() <= 1:
                    df.columns = df.columns.droplevel("Ticker")
                else:
                    # Multiple tickers somehow — pick the first
                    first_ticker = df.columns.get_level_values("Ticker")[0]
                    df = df.xs(first_ticker, level="Ticker", axis=1)
            # Guard against duplicate columns (e.g. after droplevel)
            if df.columns.duplicated().any():
                df = df.loc[:, ~df.columns.duplicated()]
            return df
        except Exception as e:
            err_str = str(e).lower()
            if "rate" in err_str or "429" in err_str or "too many" in err_str:
                # Rate limited — longer backoff
                wait = 5 * (attempt + 1)
                print(f"  [RATE] {symbol}: rate limited, waiting {wait}s...")
                time.sleep(wait)
            elif attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                print(f"  [WARN] Failed to fetch {symbol} ({period}/{interval}): {e}")
                return pd.DataFrame()


def _fill_realtime_gap(symbol, yf_df, interval):
    """Fill the gap between yfinance's last bar and now using Upstox.

    Returns combined DataFrame, or None if no gap-fill needed/possible.
    """
    from common.upstox import is_upstox_available, fetch_upstox_intraday
    from common.upstox_symbols import yf_to_upstox

    if not is_upstox_available():
        return None

    now_ist = datetime.now(IST)

    # No gap-fill outside market hours
    if now_ist.hour < 9 or (now_ist.hour == 9 and now_ist.minute < 15):
        return None
    if now_ist.hour > 15 or (now_ist.hour == 15 and now_ist.minute > 30):
        return None

    # Determine last bar time
    last_bar = yf_df.index[-1]
    if hasattr(last_bar, 'tz') and last_bar.tz is not None:
        last_bar_ist = last_bar.astimezone(IST)
    else:
        last_bar_ist = last_bar.tz_localize(IST) if hasattr(last_bar, 'tz_localize') else last_bar

    gap_seconds = (now_ist - last_bar_ist).total_seconds()
    if gap_seconds < 120:  # yfinance is fresh enough (<2 min)
        return None

    # Map symbol to Upstox instrument key
    upstox_key = yf_to_upstox(symbol)
    if not upstox_key:
        return None

    # Upstox candle APIs don't support index instruments
    if upstox_key.startswith("NSE_INDEX|"):
        return None

    # Parse interval minutes
    interval_map = {"1m": 1, "2m": 2, "5m": 5, "15m": 15}
    interval_min = interval_map.get(interval, 5)

    # Fetch Upstox intraday candles for today
    upstox_df = fetch_upstox_intraday(upstox_key, interval_min)
    if upstox_df.empty:
        return None

    # Filter to bars AFTER yfinance's last bar
    # Align timezone for comparison
    if upstox_df.index.tz is not None and (not hasattr(last_bar, 'tz') or last_bar.tz is None):
        last_bar_compare = last_bar_ist
    else:
        last_bar_compare = last_bar

    gap_bars = upstox_df[upstox_df.index > last_bar_compare]
    if gap_bars.empty:
        return None

    # Make timezone-naive to match yfinance if needed
    if yf_df.index.tz is None and gap_bars.index.tz is not None:
        gap_bars = gap_bars.copy()
        gap_bars.index = gap_bars.index.tz_localize(None)
    elif yf_df.index.tz is not None and gap_bars.index.tz is None:
        gap_bars = gap_bars.copy()
        gap_bars.index = gap_bars.index.tz_localize(IST)

    combined = pd.concat([yf_df, gap_bars])
    combined = combined[~combined.index.duplicated(keep='last')]
    return combined.sort_index()


def _try_upstox_full(symbol, period, interval):
    """Full Upstox fallback when yfinance returns nothing.

    Returns DataFrame or None.
    """
    from common.upstox import is_upstox_available, fetch_upstox_intraday, fetch_upstox_historical
    from common.upstox_symbols import yf_to_upstox

    if not is_upstox_available():
        return None

    upstox_key = yf_to_upstox(symbol)
    if not upstox_key:
        return None

    # Upstox historical/intraday candle APIs don't support index instruments
    if upstox_key.startswith("NSE_INDEX|"):
        return None

    today = datetime.now(IST).strftime("%Y-%m-%d")

    # Map (period, interval) → Upstox API calls
    if interval in ("1m", "2m", "5m", "15m"):
        interval_map = {"1m": 1, "2m": 2, "5m": 5, "15m": 15}
        return fetch_upstox_intraday(upstox_key, interval_map.get(interval, 5))

    elif interval == "1d":
        # Map period to date range
        period_days = {
            "5d": 5, "1mo": 30, "2mo": 60, "3mo": 90,
            "6mo": 180, "1y": 365, "2y": 730,
        }
        days = period_days.get(period, 180)
        from_date = (datetime.now(IST) - timedelta(days=days)).strftime("%Y-%m-%d")
        return fetch_upstox_historical(upstox_key, from_date, today, unit="days", interval=1)

    return None


def fetch_yf(symbol, period, interval, max_retries=3):
    """Download OHLCV data with cache → yfinance → Upstox gap-fill.

    Transparent to callers — same signature, same return type.
    """
    from common.data_cache import is_cache_fresh, get_cached_bars, cache_bars

    # 1. Check Supabase cache
    if is_cache_fresh(symbol, interval):
        cached = get_cached_bars(symbol, interval)
        if not cached.empty:
            return cached

    # 2. Fetch from yfinance
    yf_df = _fetch_yfinance(symbol, period, interval, max_retries)

    # 3. For intraday intervals, fill real-time gap with Upstox
    if interval in ("1m", "2m", "5m", "15m") and not yf_df.empty:
        filled = _fill_realtime_gap(symbol, yf_df, interval)
        if filled is not None:
            cache_bars(symbol, interval, filled)
            return filled

    # 4. If yfinance empty, try Upstox as full fallback
    if yf_df.empty:
        upstox_df = _try_upstox_full(symbol, period, interval)
        if upstox_df is not None and not upstox_df.empty:
            cache_bars(symbol, interval, upstox_df)
            return upstox_df

    # 5. Cache whatever we got and return
    if not yf_df.empty:
        cache_bars(symbol, interval, yf_df)
    return yf_df


def fetch_live_ltp(symbols: list[str]) -> dict[str, float]:
    """Batch LTP via Upstox. Falls back to yfinance last close.

    Returns {yf_symbol: price} dict.
    """
    from common.upstox import is_upstox_available, fetch_upstox_ltp
    from common.upstox_symbols import yf_to_upstox, upstox_to_yf

    result = {}

    # Try Upstox batch LTP
    if is_upstox_available():
        upstox_keys = {}
        for sym in symbols:
            key = yf_to_upstox(sym)
            if key:
                upstox_keys[sym] = key

        if upstox_keys:
            ltp_data = fetch_upstox_ltp(list(upstox_keys.values()))
            for sym, key in upstox_keys.items():
                if key in ltp_data:
                    result[sym] = ltp_data[key]

    # Fall back to yfinance for missing symbols
    missing = [s for s in symbols if s not in result]
    for sym in missing:
        try:
            info = yf.Ticker(sym).fast_info
            if hasattr(info, 'last_price') and info.last_price:
                result[sym] = float(info.last_price)
        except Exception:
            pass

    return result


def fetch_ticker_info(symbol):
    """Fetch ticker info dict, return empty dict on failure."""
    try:
        return yf.Ticker(symbol).info or {}
    except Exception:
        return {}


# ── Parallel / Batch Fetching ────────────────────────────────────────────

def fetch_bulk(symbols, specs, max_workers=10, label=""):
    """Fetch multiple symbols × multiple (period, interval) specs in parallel.

    Args:
        symbols: list of yfinance symbols (e.g., ["RELIANCE.NS", "TCS.NS"])
        specs: dict mapping key names to (period, interval) tuples.
               Example: {"intra": ("5d", "5m"), "daily": ("6mo", "1d")}
        max_workers: thread pool size (default 10; throttle prevents 429s)
        label: optional prefix for progress messages

    Returns:
        dict: {symbol: {spec_key: DataFrame, ...}, ...}
        Symbols that fail all retries get empty DataFrames.

    Example:
        data = fetch_bulk(
            ["RELIANCE.NS", "TCS.NS", "INFY.NS"],
            {"intra": ("5d", "5m"), "daily": ("6mo", "1d")},
        )
        data["RELIANCE.NS"]["intra"]  # → 5-day 5-min DataFrame
        data["RELIANCE.NS"]["daily"]  # → 6-month daily DataFrame
    """
    result = {sym: {k: pd.DataFrame() for k in specs} for sym in symbols}
    total_tasks = len(symbols) * len(specs)

    # Build flat task list: (symbol, spec_key, period, interval)
    tasks = []
    for sym in symbols:
        for key, (period, interval) in specs.items():
            tasks.append((sym, key, period, interval))

    completed = 0
    prefix = f"  {label} " if label else "  "

    def _do_fetch(sym, key, period, interval):
        return sym, key, fetch_yf(sym, period, interval)

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(_do_fetch, sym, key, period, interval): (sym, key)
            for sym, key, period, interval in tasks
        }
        for future in as_completed(futures):
            sym, key = futures[future]
            completed += 1
            try:
                _, _, df = future.result()
                result[sym][key] = df
            except Exception as e:
                print(f"  [WARN] {sym}/{key}: {e}")

            # Progress every 20 completions
            if completed % 20 == 0 or completed == total_tasks:
                print(f"{prefix}[{completed}/{total_tasks}] fetched")

    return result


def fetch_bulk_single(symbols, period, interval, max_workers=10, label=""):
    """Fetch one (period, interval) for many symbols in parallel.

    Convenience wrapper around fetch_bulk for the common single-spec case.

    Returns:
        dict: {symbol: DataFrame}
    """
    data = fetch_bulk(symbols, {"_": (period, interval)},
                      max_workers=max_workers, label=label)
    return {sym: data[sym]["_"] for sym in symbols}
